### ISSUE TITLE
thats a bug or not?

### ISSUE THREAD

**Issue by Dimarar** [zyledev/Candy-Engine-Public#1]
gamemaker 2 find the 107 errors 
![GameMaker_qz8DoiFMRz](https://github.com/zyledev/Candy-Engine-Public/assets/112246243/139f795a-86b0-481f-bac4-d2bee9d91a11)
this was fixeble? (im not a coder)

**Comment by zyledev** [comment]
That's feather! The errors aren't actually really errors and can be ignored.

**Comment by Dimarar** [comment]
> That's feather! The errors aren't actually really errors and can be ignored.

ohhh
